RULES.md, node/iam_password_maximum_age-periodic.js
For `node/iam_password_maximum_age-periodic.js`, the parameter key seems to be incorrect. This should resolve the documentation inconsistencies. 
=> Correct MaxPasswordLength to MaxPasswordage

node/iam_mfa_require-triggered.js
In node/iam_mfa_require-triggered.js a callback was returning `keyerr`
on error, however should have been returning `mfaerr` because of this the
lambda function would error upon hitting a non-compliant iam-user resource.
=> Correct `keyerr` to `mfaerr` in node/iam_mfa_require-triggered.js

node/iam_mfa_require_root-periodic.js
Prior to this change if the lambda role assigned to the function did not have permission to access the config bucket, it would fail without an error message.
(Also removed trailing whitespace due to Atom editor)
=> Added return on failure to retrieve getAccountSummary to avoid failing silently

RULES.md, python/ec2_require_security_group_by_tag.py
Add a new python rule that ensures all EC2 Instances that match a certain tag regex format also have a specific security group attached.
=> Add security-group by tag python rule

python/ec2-exposed-instance.py
Without the fixes above the function will throw the following error when evaluating a deleted resource
```
'NoneType' object has no attribute 'get': AttributeError Traceback (most recent call last): File "/var/task/ec2-exposed-instance.py", line 98, in lambda_handler evaluation = evaluate_compliance(configuration_item, rule_parameters) File "/var/task/ec2-exposed-instance.py", line 56, in evaluate_compliance security_groups = configuration_item["configuration"].get("securityGroups") AttributeError: 'NoneType' object has no attribute 'get'
```
And will throw the below error when evaluating any other resource due to a typo on line 33 when populating the port list.
```
can only concatenate list (not "int") to list: TypeError Traceback (most recent call last): File …
```
=> Fixed error on evaluating deleted resources and a typo in port list addition

node/cloudtrail_enabled_all_regions-periodic.js
Created constructor for readSnapshot to retrieve s3 bucket region to stop `PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint.` error when accessing config bucket from another region.  
Because the AWS Config bucket can be configured as a bucket in an external account it's possible that the home region for CloudTrail and the AWS Config bucket region may not match. Therefore I've added a constructor which finds the config bucket's S3 region in order to allow the getObject call to address the correct endpoint.  
I appreciate this PR is a little larger than my previous ones, but I welcome any feedback you have on alternative approaches!  
I confirm these files are made available under CC0 1.0 Universal …
=> Changed readSnapshot  to retrieve s3 bucket region prior to retrieval

python/ec2_require_tags_with_valid_values.py
This config rule will allow you to ensure not only the presence of defined tags (as the AWS Managed Rule), but also will let you specify a finite list of valid values for each tag.  This can be useful for enforcing that a valid CostCenter or Environment name is supplied, as arbitrary values can be used to be in compliance when only presence of tags is evaluated.
=> Adding config rule to ensure presence and values of tags

RULES.md, python/ec2_security_group_ingress.py
There are two commits in this pull request:
(1) The addition of python/ec2_security_group_ingress.py which checks that the EC2 Security Group ingress permissions are correct and adjusts them if they are incorrect.
(2) The addition of this rule as Rule 31 in RULES.md.
=> Ec2 security group

python/ec2_security_group_ingress.py
The addition of IPv6 support to Amazon VPC resulted in a change to the underlying AWS IpPermissions data structure that is provided to events generated for the AWS Config service.    The REQUIRED_PERMISSIONS data structure that appeared in the code had not been adjusted to use the new format.   As a result, the lookups performed by the code were failing because the event IpPermissions contained an additional key ("Ipv6Ranges") which was not in REQUIRED_PERMISSIONS.  I added this missing key to REQUIRED_PERMISSIONS to correct the problem.
=> Added Support for IPv6 in VPC

python/s3-exposed-bucket.py
Adding config rule to check changes tracked by AWS Config related to S3 buckets that could potentially expose data
We have seen that given some cases of data exposure people is looking for option to cover this kind of possible scenarios, AWS Config monitor for changes in the settings but do not have a default rule to look after changes in configuration on S3 resources.
Based on the information that was shared the last few weeks this config rule is instead to check is a bucket is made public, basically it checks that the permissions do not include AuthenticatedUsers or AllUsers on the ACL level plus checking that the Bucket Policy does not have a Principal=* with effect=Allow.
At this time this does not include:
* Automatic remediation
* Validation on the object level (it is really …
=> Adding config rule to check exposed buckets

python/iam-mfa.py
This rule was evaluating cli users which don't have a console password and hence cannot use MFA login mechanism. Added a check to fetch user profile before deciding on the MFA attached status. For cli user's get_login_profile will throw an exception which we can use to skip over these users.
=> Added a fix for mfa rule to only evaluate console users

python/iam-unused-keys.py
\+ Add logging for debugging purpose
\+ Wrap compliance evaluation in a try except
\! Adapt to get_resource_config_history and configuration_item API changes, no need to do the get_resource_config_history call
\! Adapt to get_access_key_last_used API changes, LastUsedDate is now wrapped in AccessKeyLastUsed
\* Push something more relevant in the Annotation string
Merging this will fix https://github.com/awslabs/aws-config-rules/issues/50.
I confirm these files are made available under CC0 1.0 Universal 
(https://creativecommons.org/publicdomain/zero/1.0/legalcode)
=> Fix iam-unused-keys.py 

python/ec2-exposed-group.py
If the source for a security group is 
`0.0.0.0/0` and the port range is `All`,
this rule will not detect the exposed group.
Also, it's good practice to check if the 
resource was deleted.
=> Exposed security groups fails if Port Range = "All"

RULES.md, python/s3_bucket_default_encryption_enabled.py
This rule checks S3 buckets for default encryption.
More on default encryption [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html).
=> Add rule to check for S3 bucket default encryption

python/ec2_launch_wizard_security_group_prohibited.py
This proposed change updates the code to handle deleted resources. Currently, if an ENI is deleted and triggers a custom AWS Config rule, the existing code will not provide a return code to remove that deleted resource. This update adds in that logic and also subsequently modifies the Security Group checks to be performed if the resource is **not** deleted.
=> Update to handle deleted resources

python/CLOUDTRAIL_ENABLED_V2/CLOUDTRAIL_ENABLED_V2_test.py
=> typo in test CLOUDTRAIL_ENABLED_V2

python/IAM_POLICY_REQUIRED/IAM_POLICY_REQUIRED.py, python/IAM_POLICY_REQUIRED/IAM_POLICY_REQUIRED_test.py, python/IAM_POLICY_REQUIRED/parameters.json
Adds a Config Rule that verifies all IAM Roles/Users have the given policy attached to them (either directly or through groups). Includes ability to exclude certain roles/users from the rule
=> Add IAM policy required config rule

python/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS.py
When iterating a split list of ports, append the ports to the `port_list` list instead of setting the list to a single port int.
=> Append ports to port_list

README.md, python/CLOUDFRONT_LOGGING_ENABLED/CLOUDFRONT_LOGGING_ENABLED_test.py
=>  correct testing on CLOUDFRONT_LOGGING_ENABLED 

python/pylintrc
Description of changes: As per CloudFormation limit on the name of the stack of 128 characters, included a limit for length of the rule name.
=> Pylintrc modified to limit length of module name

python/API_GW_EXECUTION_LOGGING_ENABLED/API_GW_EXECUTION_LOGGING_ENABLED.py, python/API_GW_EXECUTION_LOGGING_ENABLED/API_GW_EXECUTION_LOGGING_ENABLED_test.py, python/API_GW_EXECUTION_LOGGING_ENABLED/parameters.json
https://github.com/awslabs/aws-config-rules/issues/191
Adding rule API_GW_EXECUTION_LOGGING_ENABLED
=> Adding new rule API_GW_EXECUTION_LOGGING_ENABLED

python/CLOUDTRAIL_S3_DATAEVENTS_ENABLED/CLOUDTRAIL_S3_DATAEVENTS_ENABLED.py
=> Fixing CLOUDTRAIL_S3_DATAEVENTS_ENABLED to strip the bucket name for other AWS partitions as well

python/ec2_require_ebs_snapshots_for_volumes.py
The end of the file was missing a closing parenthesis.
ec2_require_ebs_snapshots_for_volumes.py has a fatal syntax error.
Added the missing closing parenthesis.
=> Added missing paren

python/ec2_require_ebs_snapshots_for_volumes.py
PutEval would fail if there were a large number of resources causing more than 100 evals.
*Issue #, if available:*  Similar to issue #103
*Description of changes:* Split evaluations into chunks of 100 or less each to avoid hitting the limit on the number of evaluations.
=> Support more than 100 evals

python/ELB_ALB_PREDEFINED_SSL_CHECK/ELB_ALB_PREDEFINED_SSL_CHECK.py
=> revert + add support for more than 100 to ELB_ALB_PREDEFINED_SSL_CHECK

python/IAM_IP_RESTRICTION/IAM_IP_RESTRICTION.py, python/IAM_IP_RESTRICTION/IAM_IP_RESTRICTION_test.py, python/IAM_IP_RESTRICTION/parameters.json
Description of changes:
IAM user's access key and secret keys are easy to target and can be stolen. As a defense, it is recommended that IAM users be IP restricted.
This custom AWS Config rule implements a check that all IAM users are IP restricted or not. if IP restricted, IAM user is marked as compliant
Follows IAM Policy rules below: 
- if IAM policy is IP denied, AWS Config marks as compliant
- if only some IAM policy is IP allowed, AWS Config marks as non compliant
- if all inline and attached IAM policy is IP allowed, AWS Config marks as compliant
=> Custom Rule IAM_IP_RESTRICTION

java/pom.xml
Upgrade com.google.guava:guava to version 24.1.1 or later. Version must be greater than or equal to 24.1.1
<dependency>
<groupId>com.google.guava</groupId>
<artifactId>guava</artifactId>
<version>[24.1.1,)</version>
</dependency>
=> Update guava version to 24.1.1

python-rdklib/EC2_TAG_VOLUMES/EC2_TAG_VOLUMES.py, python-rdklib/EC2_TAG_VOLUMES/EC2_TAG_VOLUMES_test.py, python-rdklib/EC2_TAG_VOLUMES/ec2_tag_volumes_ssm_document_executeScript.yaml, python-rdklib/EC2_TAG_VOLUMES/parameters.json
**Config Rule:** Checks whether the Amazon Elastic Block Store (EBS) volume includes the Tags from the Amazon Elastic Compute Cloud (Amazon EC2) instance, it's attached to.  The rule is NON_COMPLIANT if the volume is attached to an instance and doesn't include the instance tags. 
**SSM Automation Document:** Tags Volumes to ensure it includes the same Tags as those of the EC2 Instance its attached to.
=> EC2_TAG_VOLUMES

aws-config-conformance-packs/Operational-Best-Practices-for-Amazon-S3.yaml
For #347
#347
Fix typo on lines 58 and 61 s/ServerSideReplicationEnabled/ServerSideEncryptionEnabled
=> Fix typo ServerSideReplicationEnabled -> ServerSideEncryptionEnabled

python/API_GW_PRIVATE_RESTRICTED/API_GW_PRIVATE_RESTRICTED.py, python/API_GW_RESTRICTED_IP/API_GW_RESTRICTED_IP.py
#342 
Use gateway id instead of name in API_GW_RESTRICTED rules
=> Use gateway id instead of name in API_GW_RESTRICTED rules

python/VPC_ENDPOINT_DEFAULT_POLICY/VPC_ENDPOINT_DEFAULT_POLICY.py, python/VPC_ENDPOINT_DEFAULT_POLICY/VPC_ENDPOINT_DEFAULT_POLICY_test.py, python/VPC_ENDPOINT_DEFAULT_POLICY/parameter.json
This PR includes test that tests each VPCe (Gateway and Interface) has a resource policy attached that does not allow all actions (i.e. the default). This manages several attack vectors for bad actors to use to exfiltrate data from a compromised account.
=> Adding test for VPCe policy tests to ensure non-default policy implemented

README.md
Fixes the broken link to the CONTRIBUTING.md file.
Fixes the broken link to the CONTRIBUTING.md file.
=> Fixes Broken link in README.md

aws-config-conformance-packs/Operational-Best-Practices-for-CIS-AWS-v1.4-Level1.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CIS-AWS-v1.4-Level2.yaml
*Issue #, if available:* Remove deprecated reules
*Description of changes:* remove AccountSecurityQuestionsConfigured rules
=> Deprecate AccountSecurityQuestionsConfigured

aws-config-conformance-packs/Operational-Best-Practices-for-ABS-CCIGv2-Standard.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CCN-ENS-High.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CCN-ENS-Low.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CCN-ENS-Medium.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CMMC-2.0-Level-1.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CMMC-2.0-Level-2.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CMMC-Level-1.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CMMC-Level-2.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CMMC-Level-3.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CMMC-Level-4.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CMMC-Level-5.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-ENISA-Cybersecurity-Guide.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-Germany-C5.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-Gramm-Leach-Bliley-Act.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-MAS-Notice-655.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-NBC-TRMG.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-NCSC-CAF.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-NCSC-CloudSec-Principles.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-NIST-800-171.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-NIST-800-53-rev-4.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-NYDFS-23-NYCRR-500.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-Networking-Services.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-RBI-Basic-Cyber-Security-Framework.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-RBI-MasterDirection.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-SWIFT-CSP.yaml
*Issue #, if available:* N/A
*Description of changes:* Add AuthorizedVpcIds parameter to InternetGatewayAuthorizedVpcOnly rules
=> Add AuthorizedVpcIds parameter to InternetGatewayAuthorizedVpcOnly rules

aws-config-conformance-packs/Operational-Best-Practices-for-FedRAMP-HighPart1.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-FedRAMP-HighPart2.yaml
OW-4886
Updating the names and descriptions of the new Operational Best Practices for FedRAMP High conformance pack templates
=> Update names for FedRAMP High cpack templates

aws-config-conformance-packs/Operational-Best-Practices-For-NIST-800-181.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CIS-Critical-Security-Controls-v8-IG3.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CISA-Cyber-Essentials.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-CMMC-2.0-Level-2.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-HIPAA-Security.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-MAS-TRMG.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-NBC-TRMG.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-NIST-800-53-rev-5.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-NIST-CSF.yaml, aws-config-conformance-packs/Operational-Best-Practices-for-NIST-Privacy-Framework.yaml
Last [commit](https://code.amazon.com/packages/AwsConformsTemplates/commits/52a23701dc8f8545f21ecfcf4ac0af5784fef631) increase number of rules in some templates to 131 which is above limit of 130 rules in a CPack. 
After checking these templates found that [S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED](https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-level-public-access-prohibited.html) can be removed as the check is covered by [S3_BUCKET_PUBLIC_READ_PROHIBITED](https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-public-read-prohibited.html) and …
=> Removing S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED which is redundant to limit rules to 130
