- README.md
- node/cloudtrail_enabled_all_regions-periodic.js
- node/cloudtrail_validation_all_regions-periodic.js
- node/config_enabled_in_region-periodic.js
- node/iam_api_key_root_disabled-periodic.js
- node/iam_api_key_rotation-triggered.js
- node/iam_mfa_require-triggered.js
- node/iam_mfa_require_root-periodic.js
- node/iam_password_maximum_age-periodic.js
- node/iam_password_minimum_length-periodic.js
- node/iam_password_policy_enabled-periodic.js
- node/iam_password_require_lowercase-periodic.js
- node/iam_password_require_number-periodic.js
- node/iam_password_require_symbol-periodic.js
- node/iam_password_require_uppercase-periodic.js
- node/iam_password_reuse-periodic.js
- node/instance_desired_tenancy-triggered.js
- python/ec2_desired_instance_type-triggered.py
- python/resource_type_max_count-periodic.py
Initial commit of security related config rules including language breakouts.
> Initial commit for security related config rules.

- RULES.md
- python/vpc_flow_logs_enabled.py
This rules check that VPC Flow Logs is enabled at specified VPC
> Add rule that check vpc flow logs enabled

- RULES.md
- node/cloudtrail_enabled_all_regions-periodic.js
- node/cloudtrail_validation_all_regions-periodic.js
- node/config_enabled_in_region-periodic.js
- node/iam_access_key_root_disabled-periodic.js
- node/iam_access_key_rotation-triggered.js
- node/iam_mfa_require-triggered.js
- node/iam_mfa_require_root-periodic.js
- node/iam_password_maximum_age-periodic.js
- node/iam_password_minimum_length-periodic.js
- node/iam_password_policy_enabled-periodic.js
- node/iam_password_require_lowercase-periodic.js
- node/iam_password_require_number-periodic.js
- node/iam_password_require_symbol-periodic.js
- node/iam_password_require_uppercase-periodic.js
- node/iam_password_reuse-periodic.js
- node/instance_desired_tenancy-triggered.js
- python/ec2_desired_instance_type-triggered.py
- python/password_policy_min_password_length_CIS_benchmark_1_9-periodic.py
- python/resource_type_max_count-periodic.py
- python/vpc_flow_logs_enabled.py
Adding documentation to each lambda script.
Adding new details to RULES.md
https://github.com/awslabs/aws-config-rules/issues/7
> Documentation Updates

- node/iam_access_key_rotation-triggered.js
Updated line 9 with parameter name as given in line 71
Updated line 69 with date function
> Minor issue with parameter name & Date function

- java/HOWTO.md
- java/RULES_JAVA.md
- java/pom.xml
- java/src/main/java/com/amazonaws/services/config/samplerules/RootAccountMFAEnabled.java
- java/src/main/java/com/amazonaws/services/config/samplerules/exception/FunctionExecutionException.java
- java/src/test/java/com/amazonaws/services/config/samplerules/RootAccountMFAEnabledTest.java
This includes a Maven project under the java/ directory.
> OSS version of the ROOT_ACCOUNT_MFA_ENABLED rule in AWS Config in Java

- java/pom.xml
- java/src/main/java/com/amazonaws/services/config/samplerules/DbInstanceBackupParameters.java
- java/src/main/java/com/amazonaws/services/config/samplerules/DesiredInstanceTenancy.java
- java/src/main/java/com/amazonaws/services/config/samplerules/RootAccountMFAEnabled.java
- java/src/main/java/com/amazonaws/services/config/samplerules/exception/FunctionExecutionException.java
- java/src/test/java/com/amazonaws/services/config/samplerules/DbInstanceBackupParametersTest.java
- java/src/test/java/com/amazonaws/services/config/samplerules/DesiredInstanceTenancyTest.java
- java/src/test/java/com/amazonaws/services/config/samplerules/RootAccountMFAEnabledTest.java
- metadata/DbInstanceBackupParameters.java.json
> OSS versions of DesiredInstanceTenancy and VerifyBackupEnabled rules

- python/ec2_no_internet_access-triggered.py
New config rule flagging potential internet access as non-compliant. Has optional SNS support to trigger actions after evaluation.
> New config rule written in python

- RULES.md
- python/ec2_sg_public_ingress_excluding_80_443.py
- python/ec2_vpc_public_subnet.py
- python/rds_vpc_public_subnet.py
These new rules are added
1. Check that no security group allows public access to ports other then 80 and 443
2. Check that no EC2 are in Public Subset
3. Check that no RDS are in Public Subset
> Ensure that no EC2 is publicly accessible except 80 and 443.

- python/cloudtrail-encrypted.py
- python/cloudtrail-lfi-activated.py
> 2 New rules: CloudTrail Log File Integrity Enabled (python) + CloudTrail Encrypted (python)

- node/rds_db_instance_encrypted.js
Replaced '#' comments with '//' javascript comments
Fix incorrect quote character
Log input event and output evaluation
> Fix syntax errors, add log output

- python/config-enabled.py
- python/config-rules-exist.py
- python/iam-policy-exists.py
> 3 new rules: config-enabled, config-rule-exist, iam-policy-exist

- RULES.md
- python/ec2_launch_wizard_security_group_prohibited.py
Add a custom Config Rule to check that security groups 
prefixed with "launch-wizard" are not associated with 
network interfaces.
> Add ec2_launch_wizard_security_group_prohibited.py

- python/iam_mfa_detailed.py
- python/iam_user_pw_and_keys.py
iam_mfa_detailed
iam_user_pw_and_keys
> Add 2 new config rules

- RULES.md
- python/ec2_security_group_port_range_all_prohibited.py
- python/ec2_security_group_protocol_all_prohibited.py
This checks that inbound rules for security groups
are explicit in terms of protocol and port grange. 
A value of "All" will make a security group non-compliant.
> Add checks to prohibit port range and protocol values of "All"

- python/iam_mfa_detailed.py
- python/iam_user_pw_and_keys.py
Added more verbose instructions to the comments in these two rules
Fixed a linter warning
Changed default of debug mode to false
> More verbose instructions and fix linter warnings

- python/ec2_vpc_public_subnet.py
- python/rds_vpc_public_subnet.py
Need a second eye here but I believe the current
code produces a false positive. For example, what
if the main route table has a public route but the subnet 
is associated with a private route table?
> Fix false positive in *_vpc_public_subnet.py

- python/rds_desired_instance_type-triggered.py
Requirements: comma separated DBInstance Class named "DBInstance" as Key on Rule parameters.
> Add RDS instance Type Config Rule.

- python/iam-inactive-user.py
The current code can only be setup for the Configuration Change type of trigger. This commit adds support to use the Periodic type of trigger.
> python - iam-inactive-user: Add support for ScheduledNotification

- python/rds_public_snapshots.py
> Rule to check RDS snapshot is not shared publicly.

- python/IAM_USER_MFA_ENABLED/IAM_USER_MFA_ENABLED.py
*Issue #, if available:* #101 
*Description of changes:* adding loop to support more than 100 evaluations
> IAM_MFA to support more than 100 evals

- python/API_GW_NOT_EDGE_OPTIMISED/API_GW_NOT_EDGE_OPTIMISED.py
- python/API_GW_PRIVATE_RESTRICTED/API_GW_PRIVATE_RESTRICTED.py
- python/API_GW_RESTRICTED_IP/API_GW_RESTRICTED_IP.py
- python/DYNAMODB_ENCRYPTED/DYNAMODB_ENCRYPTED.py
- python/EMR_KERBEROS_ENABLED/EMR_KERBEROS_ENABLED.py
- python/IAM_ACCESS_KEY_ROTATED/IAM_ACCESS_KEY_ROTATED.py
- python/IAM_USER_USED_LAST_90_DAYS/IAM_USER_USED_LAST_90_DAYS.py
- python/KMS_KEY_ROTATION_ENABLED/KMS_KEY_ROTATION_ENABLED.py
- python/LAMBDA_CODE_IS_VERSIONED/LAMBDA_CODE_IS_VERSIONED.py
- python/VPC_FLOW_LOGS_ENABLED/VPC_FLOW_LOGS_ENABLED.py
> update template to support over 100 resources

- python/API_GW_NOT_EDGE_OPTIMISED/API_GW_NOT_EDGE_OPTIMISED.py
- python/API_GW_PRIVATE_RESTRICTED/API_GW_PRIVATE_RESTRICTED.py
- python/API_GW_RESTRICTED_IP/API_GW_RESTRICTED_IP.py
- python/DYNAMODB_ENCRYPTED/DYNAMODB_ENCRYPTED.py
- python/EMR_KERBEROS_ENABLED/EMR_KERBEROS_ENABLED.py
- python/IAM_ACCESS_KEY_ROTATED/IAM_ACCESS_KEY_ROTATED.py
- python/IAM_USER_MFA_ENABLED/IAM_USER_MFA_ENABLED.py
- python/IAM_USER_USED_LAST_90_DAYS/IAM_USER_USED_LAST_90_DAYS.py
- python/KMS_KEY_ROTATION_ENABLED/KMS_KEY_ROTATION_ENABLED.py
- python/LAMBDA_CODE_IS_VERSIONED/LAMBDA_CODE_IS_VERSIONED.py
- python/VPC_FLOW_LOGS_ENABLED/VPC_FLOW_LOGS_ENABLED.py
> correct testing support

- python/alb_ssl_policy.py
> To verify that the configuration of listener ssl policy of an application load balancer is correct.

- python/IAM_USER_MFA_ENABLED/IAM_USER_MFA_ENABLED.py
- python/IAM_USER_MFA_ENABLED/IAM_USER_MFA_ENABLED_test.py
> add annotation with the username

- python/lambda_require_tags_with_valid_values.py
*Description of changes:* Manual AWS Config rule to validate if mandatory tags are present in AWS Lambda function.  If the required tags are not present, flag them as non-compliant.  Please note that required permission policies (for Lambda Access and Config Rules) need to be attached to the AWS Lambda's IAM Role.
> Added file for validating required tags for lambda

- python/EBS_ENCRYPTED_VOLUMES_V2/EBS_ENCRYPTED_VOLUMES_V2.py
- python/EBS_ENCRYPTED_VOLUMES_V2/EBS_ENCRYPTED_VOLUMES_V2_test.py
> Correct subnet exception handling on EBS_ENCRYPTED_V2

- python/pylintrc
> changed regex for method name to be same as that for function name

- .gitignore
> gitignore pyc

- python/AMI_NOT_PUBLIC_CHECK/AMI_NOT_PUBLIC_CHECK.py
- python/AMI_NOT_PUBLIC_CHECK/AMI_NOT_PUBLIC_CHECK_test.py
> clean up AMI_NOT_PUBLIC_CHECK

- python/LAMBDA_INSIDE_VPC/LAMBDA_INSIDE_VPC.py
- python/LAMBDA_INSIDE_VPC/LAMBDA_INSIDE_VPC_test.py
- python/LAMBDA_INSIDE_VPC/parameters.json
#162 
Adding a new rule LAMBDA_INSIDE_VPC
> adding LAMBDA_INSIDE_VPC rule

- python/EMR_MASTER_NO_PUBLIC_IP/EMR_MASTER_NO_PUBLIC_IP.py
- python/EMR_MASTER_NO_PUBLIC_IP/EMR_MASTER_NO_PUBLIC_IP_test.py
- python/EMR_MASTER_NO_PUBLIC_IP/parameters.json
Made changes to the test file as well as the main file as per the comments
> EMR_MASTER_NO_PUBLIC_IP

- python/ELASTICACHE_REDIS_CLUSTER_AUTO_BACKUP_CHECK/ELASTICACHE_REDIS_CLUSTER_AUTO_BACKUP_CHECK.py
- python/ELASTICACHE_REDIS_CLUSTER_AUTO_BACKUP_CHECK/ELASTICACHE_REDIS_CLUSTER_AUTO_BACKUP_CHECK_test.py
- python/ELASTICACHE_REDIS_CLUSTER_AUTO_BACKUP_CHECK/parameters.json
https://github.com/awslabs/aws-config-rules/issues/150
Created and tested rule for ELASTICACHE_REDIS_CLUSTER_AUTO_BACKUP_CHECK
> Added ELASTICACHE_REDIS_CLUSTER_AUTO_BACKUP_CHECK

- python/ELASTICSEARCH_ENCRYPTED_AT_REST/ELASTICSEARCH_ENCRYPTED_AT_REST.py
- python/ELASTICSEARCH_ENCRYPTED_AT_REST/ELASTICSEARCH_ENCRYPTED_AT_REST_test.py
- python/ELASTICSEARCH_ENCRYPTED_AT_REST/parameters.json
> ELASTICSEARCH_ENCRYPTED_AT_REST - Pushing newly created rule

- python/pylintrc
> correct regex for class

- python/ELASTICSEARCH_ENCRYPTED_AT_REST/ELASTICSEARCH_ENCRYPTED_AT_REST_test.py
> remove throttle in test to go faster

- python/SNS_TOPIC_EMAIL_SUB_IN_DOMAINS/SNS_TOPIC_EMAIL_SUB_IN_DOMAINS.py
- python/SNS_TOPIC_EMAIL_SUB_IN_DOMAINS/SNS_TOPIC_EMAIL_SUB_IN_DOMAINS_test.py
- python/SNS_TOPIC_EMAIL_SUB_IN_DOMAINS/parameters.json
> Adding new rule SNS_TOPIC_EMAIL_SUB_IN_DOMAINS

- python/LAMBDA_DLQ_CHECK/LAMBDA_DLQ_CHECK.py
- python/LAMBDA_DLQ_CHECK/LAMBDA_DLQ_CHECK_test.py
- python/LAMBDA_DLQ_CHECK/parameters.json
Issue: https://github.com/awslabs/aws-config-rules/issues/165
> Initial commit LAMBDA_DLQ_CHECK

- python/EC2_SECURITY_GROUP_NOT_USED/EC2_SECURITY_GROUP_NOT_USED.py
- python/EC2_SECURITY_GROUP_NOT_USED/EC2_SECURITY_GROUP_NOT_USED_test.py
- python/EC2_SECURITY_GROUP_NOT_USED/parameters.json
> EC2_SECURITY_GROUP_NOT_USED

- python/CLOUDFRONT_VIEWER_POLICY_HTTPS/CLOUDFRONT_VIEWER_POLICY_HTTPS.py
- python/CLOUDFRONT_VIEWER_POLICY_HTTPS/CLOUDFRONT_VIEWER_POLICY_HTTPS_test.py
- python/CLOUDFRONT_VIEWER_POLICY_HTTPS/parameters.json
> CLOUDFRONT_VIEWER_POLICY_HTTPS

- python/SHIELD_ADVANCED_ENABLED_AUTORENEW/SHIELD_ADVANCED_ENABLED_AUTORENEW.py
- python/SHIELD_ADVANCED_ENABLED_AUTORENEW/SHIELD_ADVANCED_ENABLED_AUTORENEW_test.py
- python/SHIELD_ADVANCED_ENABLED_AUTORENEW/parameters.json
> Add SHIELD_ADVANCED_ENABLED_AUTORENEW

- python/SHIELD_DRT_ACCESS/SHIELD_DRT_ACCESS.py
- python/SHIELD_DRT_ACCESS/SHIELD_DRT_ACCESS_test.py
- python/SHIELD_DRT_ACCESS/parameters.json
> uploading SHIELD_DRT_ACCESS

- python/SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS/SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS.py
- python/SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS/SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS_test.py
- python/SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS/parameters.json
*Issue https://github.com/awslabs/aws-config-rules/issues/239
*Description of changes: Initial commit
> Initial push for SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS

- python/CLOUDWATCH_LOG_GROUP_ENCRYPTED/CLOUDWATCH_LOG_GROUP_ENCRYPTED.py
- python/CLOUDWATCH_LOG_GROUP_ENCRYPTED/CLOUDWATCH_LOG_GROUP_ENCRYPTED_test.py
- python/CLOUDWATCH_LOG_GROUP_ENCRYPTED/parameters.json
> initial commit for CloudWatch log group encrypted rule

- python/API_GW_CACHE_ENABLED_AND_ENCRYPTED/API_GW_CACHE_ENABLED_AND_ENCRYPTED.py
- python/API_GW_CACHE_ENABLED_AND_ENCRYPTED/API_GW_CACHE_ENABLED_AND_ENCRYPTED_test.py
- python/API_GW_CACHE_ENABLED_AND_ENCRYPTED/parameters.json
https://github.com/awslabs/aws-config-rules/issues/192
Added the new rule API_GW_CACHE_ENABLED_AND_ENCRYPTED
> Adding new rule API_GW_CACHE_ENABLED_AND_ENCRYPTED

- python/ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK/ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK.py
- python/ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK/ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK_test.py
- python/ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK/parameters.json
> Rule :: ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK

- python/CLOUDTRAIL_S3_DATAEVENTS_ENABLED/CLOUDTRAIL_S3_DATAEVENTS_ENABLED.py
- python/CLOUDTRAIL_S3_DATAEVENTS_ENABLED/CLOUDTRAIL_S3_DATAEVENTS_ENABLED_test.py
- python/CLOUDTRAIL_S3_DATAEVENTS_ENABLED/parameters.json
> Adding new rule: CLOUDTRAIL_S3_DATAEVENTS_ENABLED

- python/VPC_VPN_2_TUNNELS_UP/VPC_VPN_2_TUNNELS_UP.py
- python/VPC_VPN_2_TUNNELS_UP/VPC_VPN_2_TUNNELS_UP_test.py
- python/VPC_VPN_2_TUNNELS_UP/parameters.json
> Vpc vpn 2 tunnels up

- python/DMS_REPLICATION_NOT_PUBLIC/DMS_REPLICATION_NOT_PUBLIC.py
- python/DMS_REPLICATION_NOT_PUBLIC/DMS_REPLICATION_NOT_PUBLIC_test.py
- python/DMS_REPLICATION_NOT_PUBLIC/parameters.json
> Making the initial pull request:  DMS_REPLICATION_NOT_PUBLIC

- python/SAGEMAKER_NOTEBOOK_KMS_CONFIGURED/SAGEMAKER_NOTEBOOK_KMS_CONFIGURED.py
- python/SAGEMAKER_NOTEBOOK_KMS_CONFIGURED/SAGEMAKER_NOTEBOOK_KMS_CONFIGURED_test.py
- python/SAGEMAKER_NOTEBOOK_KMS_CONFIGURED/parameters.json
*Issue https://github.com/awslabs/aws-config-rules/issues/212
*Description of changes:* Initial commit
> Initial push for Rule: SAGEMAKER_NOTEBOOK_KMS_CONFIGURED

- .gitignore
- python/SAGEMAKER_ENDPOINT_CONFIG_KMS_KEY_CONFIGURED/SAGEMAKER_ENDPOINT_CONFIG_KMS_KEY_CONFIGURED.py
- python/SAGEMAKER_ENDPOINT_CONFIG_KMS_KEY_CONFIGURED/SAGEMAKER_ENDPOINT_CONFIG_KMS_KEY_CONFIGURED_test.py
- python/SAGEMAKER_ENDPOINT_CONFIG_KMS_KEY_CONFIGURED/parameters.json
> Sagemaker endpoint config kms key configured

- python/VPC_ENDPOINT_MANUAL_ACCEPTANCE/VPC_ENDPOINT_MANUAL_ACCEPTANCE.py
- python/VPC_ENDPOINT_MANUAL_ACCEPTANCE/VPC_ENDPOINT_MANUAL_ACCEPTANCE_test.py
- python/VPC_ENDPOINT_MANUAL_ACCEPTANCE/parameters.json
Created the periodic Rule VPC_ENDPOINT_MANUAL_ACCEPTANCE and the test file.
> Added Rule VPC_ENDPOINT_MANUAL_ACCEPTANCE.

- python/DMS_REPLICATION_NOT_PUBLIC/DMS_REPLICATION_NOT_PUBLIC_test.py
- python/ENTERPRISE_SUPPORT_PLAN_ENABLED/ENTERPRISE_SUPPORT_PLAN_ENABLED_test.py
- python/GUARDDUTY_UNTREATED_FINDINGS/GUARDDUTY_UNTREATED_FINDINGS_test.py
- python/KMS_KEYS_TO_NOT_DELETE/parameters.json
- python/S3_PUBLIC_ACCESS_SETTINGS_FOR_ACCOUNT/S3_PUBLIC_ACCESS_SETTINGS_FOR_ACCOUNT_TEST.py
- python/SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS/SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS_test.py
- python/SNS_TOPIC_EMAIL_SUB_IN_DOMAINS/SNS_TOPIC_EMAIL_SUB_IN_DOMAINS_test.py
> bug fixes in several test files

- python/DMS_REPLICATION_NOT_PUBLIC/DMS_REPLICATION_NOT_PUBLIC_test.py
- python/GUARDDUTY_UNTREATED_FINDINGS/GUARDDUTY_UNTREATED_FINDINGS_test.py
- python/SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS/SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS_test.py
> update to pass CI

- python/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS.py
- python/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS_test.py
- python/VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS/parameters.json
> iterate on code

- python/SNS_ENCRYPTED_TOPIC_CHECK/SNS_ENCRYPTED_TOPIC_CHECK.py
- python/SNS_ENCRYPTED_TOPIC_CHECK/SNS_ENCRYPTED_TOPIC_CHECK_test.py
- python/SNS_ENCRYPTED_TOPIC_CHECK/parameters.json
> SNS_ENCRYPTED_TOPIC_CHECK

- python/RDS_ENHANCED_MONITORING_ENABLED/RDS_ENHANCED_MONITORING_ENABLED.py
- python/RDS_ENHANCED_MONITORING_ENABLED/RDS_ENHANCED_MONITORING_ENABLED_test.py
- python/RDS_ENHANCED_MONITORING_ENABLED/parameters.json
*Issue #, if available:* https://github.com/awslabs/aws-config-rules/issues/244
> Initial attempt RDS_ENHANCED_MONITORING_ENABLED

- python/EKS_PUBLIC_ACCESS/parameters.json
> correct rule name

- CONTRIBUTING.md
- README.md
> Publish CONTRIBUTING.md

- README.md
- python-rdklib/README.md
> add sample directory for rdklib

- python/CLOUDFRONT_WEBACL_CHECK/CLOUDFRONT_WEBACL_CHECK.py
- python/CLOUDFRONT_WEBACL_CHECK/CLOUDFRONT_WEBACL_CHECK_test.py
- python/CLOUDFRONT_WEBACL_CHECK/parameters.json
- python/SQS_ENCRYPTION_CHECK/SQS_ENCRYPTION_CHECK.py
- python/SQS_ENCRYPTION_CHECK/SQS_ENCRYPTION_CHECK_test.py
- python/SQS_ENCRYPTION_CHECK/parameters.json
- python/SQS_TRANSIT_ENCRYPTION_CHECK/SQS_TRANSIT_ENCRYPTION_CHECK.py
- python/SQS_TRANSIT_ENCRYPTION_CHECK/SQS_TRANSIT_ENCRYPTION_CHECK_test.py
- python/SQS_TRANSIT_ENCRYPTION_CHECK/parameters.json
New config rule to check WebACL on CloudFront Distribution
> Three new config rules related to SQS encryption and WebACL on CloudFront Distribution

- python/AMI_OWNERID_CHECK/AMI_OWNERID_CHECK.py
- python/AMI_OWNERID_CHECK/parameters.json
- python/EC2_SECURITY_GROUP_BADINGRESS/EC2_SECURITY_GROUP_BADINGRESS.py
- python/EC2_SECURITY_GROUP_BADINGRESS/parameters.json
- python/ECS_AWSLOGS_CHECK/ECS_AWSLOGS_CHECK.py
- python/ECS_AWSLOGS_CHECK/parameters.json
- python/ECS_ECRIMAGE_CHECK/ECS_ECRIMAGE_CHECK.py
- python/ECS_ECRIMAGE_CHECK/parameters.json
- python/SQS_PUBLIC_ACCESS_CHECK/SQS_PUBLIC_ACCESS_CHECK.py
- python/SQS_PUBLIC_ACCESS_CHECK/SQS_PUBLIC_ACCESS_CHECK_test.py
- python/SQS_PUBLIC_ACCESS_CHECK/parameters.json
- python/WAFV2_WEBACL_LOGGING_ENABLED/WAFV2_WEBACL_LOGGING_ENABLED.py
- python/WAFV2_WEBACL_LOGGING_ENABLED/WAFV2_WEBACL_LOGGING_ENABLED_test.py
- python/WAFV2_WEBACL_LOGGING_ENABLED/parameters.json
Added SQS public access and WAFV2 WebACL logging checks
> Added ECS AWSLOGS and ECR, EC2 AMI check, SQS public access, WAFV2 WebACL logging checks and EC2 SG blacklisted ports

- python-rdklib/SECURITYHUB_ENABLED/SECURITYHUB_ENABLED.py
- python-rdklib/SECURITYHUB_ENABLED/parameters.json
Adding SECURITYHUB_ENABLED config rule
> Adding SECURITYHUB_ENABLED Config rule

- python/ECR_REPOSITORY_SCAN_ON_PUSH_CHECK/ECR_REPOSITORY_SCAN_ON_PUSH_CHECK.py
- python/ECR_REPOSITORY_SCAN_ON_PUSH_CHECK/ECR_REPOSITORY_SCAN_ON_PUSH_CHECK_test.py
- python/ECR_REPOSITORY_SCAN_ON_PUSH_CHECK/parameters.json
Add python3.7 rule for checking image scan setting on ecr repos.
> add rule for checking ecr repo image scan on push setting

- python/REDSHIFT_AUDIT_ENABLED/REDSHIFT_AUDIT_ENABLED.py
- python/REDSHIFT_AUDIT_ENABLED/REDSHIFT_AUDIT_ENABLED_test.py
- python/REDSHIFT_AUDIT_ENABLED/parameters.json
- python/REDSHIFT_DB_ENCRYPTED/REDSHIFT_DB_ENCRYPTED.py
- python/REDSHIFT_DB_ENCRYPTED/REDSHIFT_DB_ENCRYPTED_test.py
- python/REDSHIFT_DB_ENCRYPTED/parameters.json
- python/REDSHIFT_FIPS_REQUIRED/REDSHIFT_FIPS_REQUIRED.py
- python/REDSHIFT_FIPS_REQUIRED/REDSHIFT_FIPS_REQUIRED_test.py
- python/REDSHIFT_FIPS_REQUIRED/parameters.json
- python/REDSHIFT_SSL_REQUIRED/REDSHIFT_SSL_REQUIRED.py
- python/REDSHIFT_SSL_REQUIRED/REDSHIFT_SSL_REQUIRED_test.py
- python/REDSHIFT_SSL_REQUIRED/parameters.json
- python/REDSHIFT_USER_ACTIVITY_MONITORING_ENABLED/REDSHIFT_USER_ACTIVITY_MONITORING_ENABLED.py
- python/REDSHIFT_USER_ACTIVITY_MONITORING_ENABLED/REDSHIFT_USER_ACTIVITY_MONITORING_ENABLED_test.py
- python/REDSHIFT_USER_ACTIVITY_MONITORING_ENABLED/parameters.json
Added 5 config rules for Redshift:
- Audit enabled: ensure logging is enabled on the redshift cluster
- SSL required: ensure SSL is required to connect to the redshift cluster
- FIPS required:  ensure both SSL is required and FIPS ciphers are in use
- DB Encrypted: ensure the redshift cluster is encrypted 
-  User Activity Logging: ensure both audit logging and that user activity monitoring is enabled
Included both the parameters.json as well as the test cases in gherkin.
> fixed redshift config rules

- aws-config-conformance-packs/Operational-Best-Practices-for-FedRAMP-High.yaml
- aws-config-conformance-packs/Operational-Best-Practices-for-FedRAMP-Moderate.yaml
OW-4886
Launching new Operational Best Practices for FedRAMP conformance pack templates
> Launch new FedRAMP Cpack templates

- aws-config-conformance-packs/Operational-Best-Practices-for-PCI-DSS-v4.0-excluding-global-resourcetypes.yml
- aws-config-conformance-packs/Operational-Best-Practices-for-PCI-DSS-v4.0-including-global-resourcetypes.yml
V1513002015
Launching new Conformance Packs for Operational-Best-Practices-for-PCI-DSS v4.0.
> Launching new Conformance Packs for Operational-Best-Practices-for-PCI-DSS v4.0

- aws-config-conformance-packs/Operational-Best-Practices-for-BNM-RMiT.yaml
- aws-config-conformance-packs/Operational-Best-Practices-for-NZISM.yaml
P154419115
Update Operational Best Practices for NZISM to NZISM v3.8
Removing S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED from Operational-Best-Practices-for-BNM-RMiT.yaml
> Update Operational Best Practices for NZISM to NZISM v3.8
